In [1]:
import numpy as np

X = np.array(([2,9], [1,5], [3,6], [5,4]), dtype = float)
Y = np.array(([92], [86], [89], [90]), dtype=float)
y = Y/100
m, n = np.shape(Y)

print(m)
print(n)
print(X)
print(y)


def sigmoid(x):
    return 1/(1+np.exp(-x))

def derivative_sigmoid(x):
    return x*(1+x)


epoch = 100000
lr = 0.1
inputlayer_neurons = 2
hiddenlayer_neurons = 3
outputlayer_neurons = 1

wh = np.random.uniform(size = (inputlayer_neurons, hiddenlayer_neurons))
bh = np.random.uniform(size = (1, hiddenlayer_neurons))
wout = np.random.uniform(size = (hiddenlayer_neurons, outputlayer_neurons))
bout = np.random.uniform(size = (1, outputlayer_neurons))

for i in range(epoch):
    h_ip = np.dot(X, wh) +bh
    h_act = sigmoid(h_ip)
    o_ip = np.dot(h_act, wout) + bout
    output = sigmoid(o_ip)
    
    # backpropagation
    Eo = y-output
    outgrad = derivative_sigmoid(output)
    d_output = Eo*outgrad
    Eh = d_output.dot(wout.T)
    hiddengrad = derivative_sigmoid(h_act)
    d_hidden = Eh*hiddengrad
    
    wout+=h_act.T.dot(d_output) * lr
    wh+= X.T.dot(d_hidden) * lr

print(wout)
print(wh)
print(" Normal Input  \n", str(X))
print(" Actual Output \n", str(y))
print(" Predicted Output \n", output)


4
1
[[2. 9.]
 [1. 5.]
 [3. 6.]
 [5. 4.]]
[[0.92]
 [0.86]
 [0.89]
 [0.9 ]]
[[0.40512892]
 [0.6275456 ]
 [0.82128409]]
[[ 719.59913612 1113.90019669 1457.89684824]
 [1369.6575512  2122.08618043 2776.96059582]]
 Normal Input  
 [[2. 9.]
 [1. 5.]
 [3. 6.]
 [5. 4.]]
 Actual Output 
 [[0.92]
 [0.86]
 [0.89]
 [0.9 ]]
 Predicted Output 
 [[0.8925]
 [0.8925]
 [0.8925]
 [0.8925]]
